title: Natasha Yamane
logo: /assets/img/logo.png
description: Personal website of Natasha Yamane
show_downloads: false
google_analytics: G-KM6MLQZBP2
remote_theme: gebeto/researcher

footer: "&copy; 2021 Natasha Yamane. Last updated on Mar 1, 2021."
# footer_url: "https://github.com/ankitsultana"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
